name: PR Build

on:
  pull_request:

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 21.7.3
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.3

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
